# Inserts a blank line between shell prompts

#add_newline = true

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[python]
disabled = false
format = "‚û§ [$symbol($version )]($style)"

[lua]
disabled = false
format = "‚û§ [$symbol($version )]($style)"

[nodejs]
disabled = false
format = "‚û§ [$symbol($version )]($style)"

[ruby]
disabled = false
format = "‚û§ [$symbol($version )]($style)"

[ocaml]
disabled = false
format = "‚û§ [$symbol($version )]($style)"

# Replace the "‚ùØ" symbol in the prompt with "‚ûú"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[Œª](white)"     # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"
error_symbol = "[Œª](bold red)"
vicmd_symbol = "[Œª](blue)"

# configure directory
[directory]
truncation_length = 10
truncate_to_repo = false # truncates directory to root folder if in github repo
home_symbol = "‚ü∞"
style = "italic #565f90"

[git_branch]
style="italic bold  yellow"

# docker
[docker_context]
symbol = "üêã "
disabled = false


