format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$cmd_duration\
$character"""

[cmd_duration]
format="[$duration ]($style)"

#add_newline = true

[line_break]
disabled = true

[character]
success_symbol = "[λ](#565f90)"
error_symbol = "[λ](bold red)"
vicmd_symbol = "[λ](#5087cc)"
vimcmd_replace_one_symbol = "[λ](#5087cc)"
vimcmd_replace_symbol = "[λ](#5087cc)"
vimcmd_visual_symbol = "[λ](#5087cc)"

[directory]
truncation_length = 10
truncate_to_repo = true
home_symbol = ""
style = "#565f90"

[git_branch]
style="italic bold  yellow"
format="[$symbol$branch(:$remote_branch)]($style) "

[hg_branch]
style="italic bold  yellow"
