return {
  require "plugins.tokyonight",
  require "plugins.cmp_snip",
  require "plugins.lsp",
  require "plugins.dap",
  require "plugins.ui",
  require "plugins.flutter",
  require "plugins.git",
  require "plugins.leap",
  require "plugins.lualine",
  require "plugins.misc",
  require "plugins.null-ls",
  require "plugins.nvim-colorizer",
  require "plugins.telescope",
  require "plugins.tree",
  require "plugins.treesitter",
}
