
alias cat='bat -p'
alias less='bat'
alias vim='nvim'
alias copy='xclip -sel clip'
alias vi='nvim'
alias grep='rg'
alias pacman='pamac'
alias pac='pamac'
alias fdh="fd -H"
alias so="exec"
alias ta='tmux attach'
alias tksv='tmux kill-server'
alias tl='tmux list-sessions'
alias clear='echo "DONOT CLEAR USE CONTROL l"'
alias ts='ns && tmux new'
alias t='tmux'
alias rg='rg -i'
alias open='xdg-open $@ 2> /dev/null'
