
alias cat='bat -p'
alias less='bat'
alias vim='nvim'
alias emc='emacsclient -nc'
alias copy='xclip -sel clip'
alias vi='nvim'
alias grep='rg'
alias pacman='pamac'
alias pac='pamac'
alias fdh="fd -H"
alias ta='tmux attach'
alias tksv='tmux kill-server'
alias tl='tmux list-sessions'
alias ts='ns && tmux new'
alias t='tmux'
alias rg='rg -i'
alias open='xdg-open $@ 2> /dev/null'
alias htop='btop'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
